name: deploy-dev
on:
  push:
    branches:
      -master
  workflow_dispatch:
jobs:
  deploy-dev:
    runs-on: -runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Context for Buildx
        run: |
          docker context create custom_context
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          endpoint: custom_context
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./Dockerfile 
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vwd-dc:latest

      - name: Deploy to Development Environment
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/vwd-dc:latest
          docker stop vwd-dc || true
          docker rm vwd-dc || true
          docker run -d --name vwd-dc -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/vwd-dc:latest
     
          
