name: deploy-dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vwd-dc:latest

      - name: Deploy to Development Environment
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/vwd-dc:latest
          docker stop vwd-dc || true
          docker rm vwd-dc || true
          docker run -d --name vwd-dc -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/vwd-dc:latest

      - name: Check Container Logs
        run: docker logs vwd-dc

      - name: Health Check
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8080 >/dev/null; then
              echo "Application is up!"
              exit 0
            fi
            echo "Waiting for application..."
            sleep 5
          done
          echo "Application did not start in time."
          exit 1

      - name: Inspect Running Containers
        run: docker ps -a
