name: Deploy Docker Container to Azure VM

on:
  push:
    branches:
      - master  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile  # Adjust if your Dockerfile is located elsewhere
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vwd-dc:latest

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull amit007pra/vwd-dc:latest
            docker stop bits || true
            docker rm bits || true
            docker run -d --name bits -p 8080:8080 amit007pra/vwd-dc:latest
