name: Deploy Docker Container to Azure VM

on:
  push:
    branches:
      - master 

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vwd-dc:latest

  Deploy: 
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo chmod 777 -R /var/run/docker.sock
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/vwd-dc:latest
            docker stop bits || true
            docker rm bits || true
            docker run -d --name bits -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/vwd-dc:latest

  HawkScan:
    name: HawkScan Security Scan
    runs-on: ubuntu-latest
    needs: Deploy
    steps:
      # Step 1: Clone your repository
      - name: Clone repo
        uses: actions/checkout@v3
  
      # Step 2: Set up OpenJDK 8
      - name: Java setup 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # You can use 'adoptopenjdk' or 'temurin', both support JDK 8
      - name: snyk test
        continue-on-error: true
        run: |-
          npm install snyk -g
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk code test
  
      # Step 3: Run HawkScan security scan with StackHawk action
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
