name: Deploy Docker Container to Azure VM

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} .
          docker 

      - name: Push Docker image to Docker Hub
        run: |
         docker push amit007pra/vwd-dc:latest

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull amit007pra/vwa:latest
            docker stop vwa || true
            docker rm vwa || true
            docker run -d --name vwa -p 8080:8080 amit007pra/vwa:latest
