name: Build and deploy Java app to Tomcat with MySQL

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'  # Adjusted to Java 11 as Java 1.7 is no longer supported in most modern environments
          distribution: 'temurin'

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          java-version: '7'
          distribution: 'adopt'

      - name: Install MySQL Server
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server

      - name: Start MySQL Service
        run: sudo systemctl start mysql

      - name: Configure MySQL Database
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          sudo mysql -e "CREATE DATABASE dvja;"
          sudo mysql -e "CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON dvja.* TO '${MYSQL_USER}'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Import Schema
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          mysql -u $MYSQL_USER -p$MYSQL_PASSWORD dvja < ./db/schema.sql

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 1.7
        uses: actions/setup-java@v4
        with:
          java-version: '7'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR file for deployment
        uses: actions/upload-artifact@v4
        with:
          name: vwadc-app
          path: ${{ github.workspace }}/target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Download WAR file
        uses: actions/download-artifact@v4
        with:
          name: dvja-app

      - name: Deploy to Tomcat
        run: |
          sudo apt-get install -y tomcat9
          sudo cp ./target/vwadc-app.war /var/lib/tomcat9/webapps/ROOT.war
          sudo service tomcat9 restart
